//+------------------------------------------------------------------+
//| VSA_LR_Backtest_Replay_EA.mq5                                    |
//| Replays untouched Python VSA setups in the MT5 Strategy Tester.  |
//| UseMLFilter=true tests VSA+LR; false tests the VSA-only baseline. |
//| Educational evaluation only. No profit guarantee.                |
//+------------------------------------------------------------------+
#property strict
#property tester_file "vsa_lr_test_signals.csv"

#include <Trade/Trade.mqh>

input string SignalFileName = "vsa_lr_test_signals.csv";
input bool UseMLFilter = true;
input double LRThreshold = 0.35;
input bool UseStrategyRiskSizing = false;
input double FixedLots = 0.01;
input bool OnePositionAtATime = true;
input long MagicNumber = 260818;
input int MaximumReplayDelayMinutes = 10;

CTrade trade;

datetime signal_times[];
string signal_directions[];
int signal_scenarios[];
double signal_probabilities[];
double signal_risk_percent[];
double signal_source_entry[];
double signal_stop[];
double signal_source_tp1[];
double signal_source_tp4[];
int signal_python_candidate[];

int signal_count = 0;
int next_signal = 0;
int candidates_seen = 0;
int ml_rejected = 0;
int execution_skipped = 0;
int orders_opened = 0;
datetime last_bar_time = 0;

bool managed_position = false;
bool partial_completed = false;
double managed_tp1 = 0.0;
double managed_tp4 = 0.0;
double managed_entry = 0.0;

double NormalizeVolume(double volume)
{
   double min_volume = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double max_volume = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   if(step <= 0.0) return 0.0;
   volume = MathFloor(volume / step + 1e-9) * step;
   return MathMax(min_volume, MathMin(max_volume, volume));
}

double RiskBasedVolume(double entry, double stop, double risk_percent)
{
   double tick_size = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double tick_value = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double distance = MathAbs(entry - stop);
   if(tick_size <= 0.0 || tick_value <= 0.0 || distance <= 0.0 || risk_percent <= 0.0)
      return 0.0;
   double risk_money = AccountInfoDouble(ACCOUNT_BALANCE) * risk_percent / 100.0;
   double loss_per_lot = distance / tick_size * tick_value;
   if(loss_per_lot <= 0.0) return 0.0;
   double raw_volume = risk_money / loss_per_lot;
   if(raw_volume < SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN)) return 0.0;
   return NormalizeVolume(raw_volume);
}

bool LoadReplaySignals()
{
   int handle = FileOpen(SignalFileName, FILE_READ|FILE_CSV|FILE_ANSI, ',', CP_UTF8);
   if(handle == INVALID_HANDLE)
   {
      Print("Cannot open tester replay file: ", SignalFileName, " error=", GetLastError());
      return false;
   }

   // Ten-column header generated by scripts/export_mt5_backtest_replay.py.
   for(int field=0; field<10 && !FileIsEnding(handle); field++)
      FileReadString(handle);

   while(!FileIsEnding(handle))
   {
      string time_text = FileReadString(handle);
      if(StringLen(time_text) < 10) break;
      string direction = FileReadString(handle);
      int scenario = (int)StringToInteger(FileReadString(handle));
      double probability = StringToDouble(FileReadString(handle));
      double risk_percent = StringToDouble(FileReadString(handle));
      double source_entry = StringToDouble(FileReadString(handle));
      double stop_price = StringToDouble(FileReadString(handle));
      double source_tp1 = StringToDouble(FileReadString(handle));
      double source_tp4 = StringToDouble(FileReadString(handle));
      int python_candidate = (int)StringToInteger(FileReadString(handle));

      StringReplace(time_text, "-", ".");
      datetime parsed_time = StringToTime(time_text);
      if(parsed_time <= 0 || (direction != "BUY" && direction != "SELL"))
      {
         Print("Skipping malformed replay row at index ", signal_count);
         continue;
      }

      int size = signal_count + 1;
      ArrayResize(signal_times, size);
      ArrayResize(signal_directions, size);
      ArrayResize(signal_scenarios, size);
      ArrayResize(signal_probabilities, size);
      ArrayResize(signal_risk_percent, size);
      ArrayResize(signal_source_entry, size);
      ArrayResize(signal_stop, size);
      ArrayResize(signal_source_tp1, size);
      ArrayResize(signal_source_tp4, size);
      ArrayResize(signal_python_candidate, size);

      signal_times[signal_count] = parsed_time;
      signal_directions[signal_count] = direction;
      signal_scenarios[signal_count] = scenario;
      signal_probabilities[signal_count] = probability;
      signal_risk_percent[signal_count] = risk_percent;
      signal_source_entry[signal_count] = source_entry;
      signal_stop[signal_count] = stop_price;
      signal_source_tp1[signal_count] = source_tp1;
      signal_source_tp4[signal_count] = source_tp4;
      signal_python_candidate[signal_count] = python_candidate;
      signal_count++;
   }
   FileClose(handle);
   Print("Loaded ", signal_count, " untouched-test VSA replay setups. UseMLFilter=", UseMLFilter,
         ", LRThreshold=", DoubleToString(LRThreshold, 2));
   return signal_count > 0;
}

bool IsManagedPositionSelected()
{
   if(!PositionSelect(_Symbol)) return false;
   return (long)PositionGetInteger(POSITION_MAGIC) == MagicNumber;
}

bool ClosePartialVolume(double close_volume, ENUM_POSITION_TYPE position_type)
{
   ENUM_ACCOUNT_MARGIN_MODE mode = (ENUM_ACCOUNT_MARGIN_MODE)AccountInfoInteger(ACCOUNT_MARGIN_MODE);
   if(mode == ACCOUNT_MARGIN_MODE_RETAIL_HEDGING)
      return trade.PositionClosePartial(_Symbol, close_volume);

   if(position_type == POSITION_TYPE_BUY)
      return trade.Sell(close_volume, _Symbol, 0.0, 0.0, 0.0, "VSA close 70% at 1R");
   return trade.Buy(close_volume, _Symbol, 0.0, 0.0, 0.0, "VSA close 70% at 1R");
}

void ManagePosition()
{
   if(!managed_position) return;
   if(!IsManagedPositionSelected())
   {
      managed_position = false;
      partial_completed = false;
      return;
   }
   if(partial_completed) return;

   ENUM_POSITION_TYPE position_type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
   double current = position_type == POSITION_TYPE_BUY
                    ? SymbolInfoDouble(_Symbol, SYMBOL_BID)
                    : SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   bool reached = position_type == POSITION_TYPE_BUY ? current >= managed_tp1 : current <= managed_tp1;
   if(!reached) return;

   double volume = PositionGetDouble(POSITION_VOLUME);
   double minimum = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double close_volume = NormalizeVolume(volume * 0.70);
   if(close_volume >= volume || volume - close_volume < minimum)
   {
      Print("Cannot preserve a 30% runner at the broker's minimum lot size; position remains managed to 4R.");
      partial_completed = true;
      return;
   }
   if(!ClosePartialVolume(close_volume, position_type))
   {
      Print("70% close failed: ", trade.ResultRetcode(), " ", trade.ResultRetcodeDescription());
      return;
   }

   if(IsManagedPositionSelected())
   {
      if(!trade.PositionModify(_Symbol, managed_entry, managed_tp4))
         Print("Breakeven modification failed: ", trade.ResultRetcodeDescription());
      else
         Print("70% closed at 1R; remaining 30% moved to breakeven with target at 4R.");
   }
   partial_completed = true;
}

void ExecuteSignal(int index)
{
   candidates_seen++;
   double probability = signal_probabilities[index];
   if(UseMLFilter && probability < LRThreshold)
   {
      ml_rejected++;
      Print("LR rejected VSA setup ", TimeToString(signal_times[index]), " probability=",
            DoubleToString(probability, 3));
      return;
   }
   if(OnePositionAtATime && PositionSelect(_Symbol))
   {
      execution_skipped++;
      Print("Setup skipped because a position is already open: ", TimeToString(signal_times[index]));
      return;
   }

   MqlTick tick;
   if(!SymbolInfoTick(_Symbol, tick))
   {
      execution_skipped++;
      return;
   }
   bool buy = signal_directions[index] == "BUY";
   double entry = buy ? tick.ask : tick.bid;
   double stop = signal_stop[index];
   if((buy && stop >= entry) || (!buy && stop <= entry))
   {
      execution_skipped++;
      Print("Setup skipped because replay stop is invalid after the next-bar market entry.");
      return;
   }

   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   double distance = MathAbs(entry - stop);
   double tp1 = buy ? entry + distance : entry - distance;
   double tp4 = buy ? entry + 4.0 * distance : entry - 4.0 * distance;
   stop = NormalizeDouble(stop, digits);
   tp1 = NormalizeDouble(tp1, digits);
   tp4 = NormalizeDouble(tp4, digits);

   double lots = UseStrategyRiskSizing
                 ? RiskBasedVolume(entry, stop, signal_risk_percent[index])
                 : NormalizeVolume(FixedLots);
   if(lots <= 0.0)
   {
      execution_skipped++;
      Print("Setup skipped because position size is invalid.");
      return;
   }

   string mode = UseMLFilter ? "VSA+LR" : "VSA-only";
   string comment = mode + " S" + IntegerToString(signal_scenarios[index]);
   bool sent = buy
               ? trade.Buy(lots, _Symbol, 0.0, stop, tp4, comment)
               : trade.Sell(lots, _Symbol, 0.0, stop, tp4, comment);
   if(!sent)
   {
      execution_skipped++;
      Print("Order failed: ", trade.ResultRetcode(), " ", trade.ResultRetcodeDescription());
      return;
   }

   orders_opened++;
   managed_position = true;
   partial_completed = false;
   managed_entry = entry;
   managed_tp1 = tp1;
   managed_tp4 = tp4;
   Print(mode, " opened ", signal_directions[index], " Scenario ", signal_scenarios[index],
         " probability=", DoubleToString(probability, 3), " lots=", DoubleToString(lots, 2));
}

int OnInit()
{
   if(_Period != PERIOD_M5)
   {
      Print("Attach this benchmark EA to XAUUSD M5 only.");
      return INIT_PARAMETERS_INCORRECT;
   }
   trade.SetExpertMagicNumber(MagicNumber);
   trade.SetTypeFillingBySymbol(_Symbol);
   if(!LoadReplaySignals()) return INIT_FAILED;
   return INIT_SUCCEEDED;
}

void OnTick()
{
   ManagePosition();
   datetime current_bar = iTime(_Symbol, PERIOD_M5, 0);
   if(current_bar <= 0 || current_bar == last_bar_time) return;
   last_bar_time = current_bar;

   while(next_signal < signal_count && signal_times[next_signal] < current_bar)
   {
      int age_minutes = (int)((current_bar - signal_times[next_signal]) / 60);
      if(age_minutes <= MaximumReplayDelayMinutes)
         ExecuteSignal(next_signal);
      else
      {
         execution_skipped++;
         Print("Missed replay setup outside allowed delay: ", TimeToString(signal_times[next_signal]));
      }
      next_signal++;
   }
}

void OnDeinit(const int reason)
{
   Print("VSA replay summary: candidates=", candidates_seen,
         ", ML rejected=", ml_rejected,
         ", execution skipped=", execution_skipped,
         ", orders opened=", orders_opened);
}

double OnTester()
{
   return TesterStatistics(STAT_PROFIT_FACTOR);
}
